version: '3.1'

services:
  etcd:
    image: 'bitnami/etcd:3.4.0'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
#      - ETCDCTL_API=2
    ports:
      - 2379:2379
      - 2380:2380
#    networks:
#      - app-tier